[package]
name = "shell"
version = "0.1.0"
authors = []
edition = "2021"

[dependencies]
os_pipe = "1.1.2"
termion = "1.5.5"
unicode-width = "0.1.5"
unicode-segmentation = "1.7.1"
which = "4.4.0"
csv = "1.2.1"
json = "0.12.4"

[[bin]]
name = "run"
path = "src/terminal.rs"